{
 "title": "task-2-54-dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  kube_pod_status_phase{\n    namespace=\"$namespace\",\n    phase=\"Running\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "sum(\n  container_memory_working_set_bytes{\n    namespace=\"$namespace\",\n    container!=\"\"\n  }\n) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Restart Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod)(\n  increase(\n    kube_pod_container_status_restarts_total{\n      namespace=\"$namespace\"\n    }[1h]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    container_cpu_usage_seconds_total{\n      namespace=\"$namespace\",\n      container!=\"\"\n    }[5m]\n  )\n) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"$namespace\"} |= \"error\""
    }
   ]
  }
 ]
}